r"""Toeplitz machinery: weights, forward/adjoint, projections, Cadzow denoiser.

T_P(x) is the (N-P) x (P+1) Toeplitz matrix generated by the length-N vector x.
Gamma = diag(w) with w = toeplitz_weights(N, P) makes T_P an isometry from
(C^N, ||.||_Gamma) onto (T_P, ||.||_F).
"""

import numpy as np
from numpy.linalg import svd


def toeplitz_weights(N, P):
    r"""Diagonal multiplicities w_i of T_P: ||T_P(x)||_F^2 = sum_i w_i |x_i|^2."""
    m, n = N - P, P + 1
    i = np.arange(N)
    return np.minimum.reduce([i + 1,
                              np.full(N, m),
                              np.full(N, n), N - i]).astype(float)


def build_toeplitz(x, N, P):
    r"""Build the (N-P) x (P+1) Toeplitz matrix T_P(x) from length-N vector x.

    Convention: A[r, c] = x[r - c + P], r=0..N-P-1, c=0..P.
    """
    m, n = N - P, P + 1
    r = np.arange(m)[:, None]
    c = np.arange(n)[None, :]
    idx = r - c + P
    return x[idx]


def toeplitz_adjoint_read(A, N, P):
    r"""Sum-along-diagonals map: unnormalized adjoint of build_toeplitz."""
    m, n = N - P, P + 1
    x = np.zeros(N, dtype=complex)
    r = np.arange(m)[:, None]
    c = np.arange(n)[None, :]
    idx = (r - c + P).ravel()
    np.add.at(x, idx, A.ravel())
    return x


def project_toeplitz(A, N, P, w):
    r"""Orthogonal (Frobenius) projection of A onto the Toeplitz subspace."""
    x = toeplitz_adjoint_read(A, N, P) / w
    return build_toeplitz(x, N, P)


def project_rank(A, K):
    r"""Projection onto rank-<=K matrices (truncated SVD)."""
    U, s, Vh = svd(A, full_matrices=False)
    s[K:] = 0.0
    return (U * s) @ Vh


def cadzow_denoiser(x, N, P, K, n_iter, w):
    r"""H_n(x) = T_P^+ (Pi_{T_P} Pi_{H_K})^n T_P(x); returns length-N vector."""
    A = build_toeplitz(x, N, P)
    for _ in range(n_iter):
        A = project_rank(A, K)
        A = project_toeplitz(A, N, P, w)
    return toeplitz_adjoint_read(A, N, P) / w
